<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RollForward>Major</RollForward>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <AssemblyName>HealthMailer.Tests</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\apps\HealthMailer\HealthMailer.csproj" />
    <ProjectReference Include="..\..\installers\PrintRxerSuiteInstaller\PrintRxerSuiteInstaller.csproj" />
  </ItemGroup>
</Project>
