<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RollForward>Major</RollForward>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>printRxerInstaller</AssemblyName>
    <RootNamespace>PrintRxerV3Installer</RootNamespace>
    <PlatformTarget>x64</PlatformTarget>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>..\..\assets\branding\mncms.ico</ApplicationIcon>
  </PropertyGroup>
</Project>
